version: "3"
services:
  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
